version: '3.6'
services:
    torch-services:
        container_name: torchservices
        image: edrudi97/torchservices:v0.6.0
        networks:
         - torch-net    
networks:
  torch-net:
    name: torch-net
    driver: bridge
